server:
  port: 5560

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/

spring:
  application:
    name: helloclient

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream