server:
  port: 5556
  requestLimit: 2

spring:
  application:
    name: helloserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/
  instance:
      prefer-ip-address: true